[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/"
] 



optimizer = true                                      
optimizer_runs = 1
fuzz-runs = 100000        
                                   
fuzz_max_local_rejects = 65536                               
fuzz_max_global_rejects = 1024                              

# See more config options https://github.com/foundry-rs/foundry/tree/master/config